### ISSUE TITLE
unnecessary files needs Deletion

### ISSUE THREAD

**Issue by Ashfinn** [MRH-Romit/Guess-The-District#2]
1. There are unnecessary python files that don't need to be on the repo for the app to run. 
2. The `squirrel_count.csv` file has a data missing.

**Comment by MRH-Romit** [comment]
So, you saw that I didn't even start on the district repo;  still opening an issue. Valorant is destroying you, play Counter Strike 2 instead of that game

**Comment by flugel0007** [comment]
i want ur gyatt 😋
