### ISSUE TITLE
Code Improvement Suggestions

### ISSUE THREAD

**Issue by Ashfinn** [MRH-Romit/Guess-The-District#3]
**Description**
The current implementation of main.py works as intended but could benefit from several improvements to enhance its structure, readability, documentation, and error handling.

**Suggested Improvements:**

1. Fixing the Code Structure:
    - Refactor the code into modular functions to separate concerns and improve maintainability.
    - Following Best Practices to Improve Readability:

2. Use descriptive variable and function names.
    - Ensure consistent use of indentation and spacing.

3. Adding Better Documentation:
    - Include docstrings for all functions to describe their purpose, parameters, and return values.
    - Add comments to explain non-obvious parts of the code.

4. Adding Error Handling Systems:
    - Implement try-except blocks to handle potential errors, such as file not found or data read issues.
    - Provide meaningful error messages to help with debugging.

**Comment by Ashfinn** [comment]
@MRH-Romit oi mama review pls

**Comment by MRH-Romit** [comment]
reviewed , shera parle purada banai de , arr bhalo lagtese na duniya, y dont i have any GF TwT
